# single_speaker_data_path = '/home/smg/v-antoine/Data/SIWIS_preprocessed_waveRNN_fixed/' 
single_speaker_data_path = '/home/smg/v-antoine/Data/French_Multi_waveRNN_preprocessed/' 
sample_rate = 24000
n_fft = 2048
fft_bins = 1025
num_mels = 80
hop_length = 288
win_length = 1200
fmin = 0
fmax = 8000
min_level_db = -100
ref_level_db = 20
upsample_factors = (9, 8, 4)
# checkpoint_dir = "waveRNN_SIWIS_fixed_checkpoints"
# output_dir="waveRNN_SIWIS_fixed_outputs"
checkpoint_dir = "waveRNN_ATR_French_Multi_checkpoints"
output_dir="waveRNN_ATR_French_Multi_outputs"
batch_size=64
rnn_dims=1024
fc_dims=1024
lr=1e-4
